title: duaneking.github.io
github_username:  duaneking
description: duaneking.github.io
theme: jekyll-theme-hacker
baseurl: ""
url: ""
plugins:
  - jekyll-feed
  - jekyll-optional-front-matter 
exclude:
  - .env
  - .gitignore
