title: duaneking.github.io
github_username:  duaneking
description: ToDo: A description fit for this.
theme: jekyll-theme-hacker
baseurl: ""
url: ""
plugins:
  - jekyll-feed
exclude:
  - .env
  - .gitignore
