collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      author: "duane"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "duane"
  - scope:
      path: ""
    values:
      layout: "default"
      author: "duane"
title: duaneking.github.io
github_username:  duaneking
description: duaneking.github.io
theme: jekyll-theme-hacker
baseurl: ""
url: ""
plugins:
  - jekyll-feed
  - jekyll-optional-front-matter 
exclude:
  - .env
  - .gitignore
